name: Cucumber
on: push
jobs:
  cucumber_a:
    name: Run Tests Group A
    uses: './.github/workflows/cucumber-tests-job.yml'
    with:
      run-cmd: |
        bundle exec cucumber --strict HEADLESS=true HOST=localhost staff_features/accessions/accession_create.feature
