name: Cucumber
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cucumber_a_g:
    name: Run Tests Group A - G
    uses: './.github/workflows/cucumber-tests-job.yml'
    with:
      run-cmd: |
        dirs=$(find ./staff_features -mindepth 1 -maxdepth 1 -type d -iname '[a-g]*' | tr '\n' ' ')
        if [ -n "$dirs" ]; then
          bundle exec cucumber --strict HEADLESS=true HOST=localhost $dirs
        fi
  cucumber_h_m:
    name: Run Tests Group H - M
    uses: './.github/workflows/cucumber-tests-job.yml'
    with:
      run-cmd: |
        dirs=$(find ./staff_features -mindepth 1 -maxdepth 1 -type d -iname '[h-m]*' | tr '\n' ' ')
        if [ -n "$dirs" ]; then
          bundle exec cucumber --strict HEADLESS=true HOST=localhost $dirs
        fi
  cucumber_n_s:
    name: Run Tests Group N - S
    uses: './.github/workflows/cucumber-tests-job.yml'
    with:
      run-cmd: |
        dirs=$(find ./staff_features -mindepth 1 -maxdepth 1 -type d -iname '[n-s]*' | tr '\n' ' ')
        if [ -n "$dirs" ]; then
          bundle exec cucumber --strict HEADLESS=true HOST=localhost $dirs
        fi
  cucumber_t_z:
    name: Run Tests Group T - Z
    uses: './.github/workflows/cucumber-tests-job.yml'
    with:
      run-cmd: |
        dirs=$(find ./staff_features -mindepth 1 -maxdepth 1 -type d -iname '[t-z]*' | tr '\n' ' ')
        if [ -n "$dirs" ]; then
          bundle exec cucumber --strict HEADLESS=true HOST=localhost $dirs
        fi
